### ISSUE TITLE
Feature Request: Zone Pause on Self Buffs

### ISSUE THREAD

**Issue by Panda671** [nomns/nparse#1]
So an issue I run into with GINA is that if you zone there is no way to pause the timers, so they keep running. This makes them slightly inaccurate. Each time you zone they get further ahead. Would it be possible to implement a pause for your own buffs when zoning?

**Comment by nomns** [comment]
As per my numerous stealthy additions to Usage and Instructions, this is something I didn't want to do because it wouldn't be universally trackable on all of your targets, but I am beginning to see the value for sure.   Its super easy to calculate, but I will have to change the way a couple things are done to implement it.  It will only affect self buffs as you say.

I will have this feature released this Sunday (02/18/18) at some point.  Hopefully it will be pared with an actual settings window for the main program to edit small things like warning/alert sounds that are planned and the ability turn on/off more minute features such as this.

**Comment by nomns** [comment]
This is implemented and is currently defaulted as on.  It will be in the release on Sunday.

A couple of items after testing.  The time in which your spell is elongated by the server compared to actual time passing seems to be off a little.  This could be a situation because of the server tick, but I am not entirely 100%.  Maybe it starts counting down prior to your client showing the zone in?

For example: 

When using a spell like Yaulp, I was able to zone 4 times before the buff wore off on the character but I was only actually not zoning for ~ 7 seconds.  Yaulp should last 3-4 ticks (18-24 seconds).  So, somehow it is being cut short of its full duration.  On one attempt, I zoned with 9 seconds remaining, and zoned in with the buff wearing off.  

I've tested on Lull with a 2 minute timer and then zoned about 10 times @ around 13 seconds per zone, and Lull wore off within 5 seconds of the timer saying it should have 3 times in a row, so maybe the tick thing is more specific to shorter cast time's like Yaulp. 

Either way, the spell wear off time for self buffs will be much more accurate if you zone.

**Comment by Panda671** [comment]
Interesting. Server ticks do seem to mess with things quite frequently. Thank you for your work.

Off topic from this feature request, have you ever considered doing floating damage text? I feel like it would be fairly simple to parse through the log.

You could have an overlay for incoming and outgoing damage, heals, etc.

**Comment by nomns** [comment]
We are talking self damage only?  Like the interface huds from wow? example: 3 'window' overlays where the left shows incoming, right shows outgoing and center shows alerts like you dodge, you parry, etc?  So left would grow down and fade, right would grow up and fade, and center would grow and fade relative to its position?

It would be pretty simple to create one window that housed all self text in one overlay rather than split into 3.  You could give options for font face, size, grow direction, etc?

Does it show in text how much you are healed if someone else heals you?

I did plan on doing something with damage, but it is def. a little lower on my list.  What I am working on atm is an actual settings window (settings intervals/overlay opacity, etc.) and implementing sounds for better alerts.  So hopefully after I finish those items, I can start looking at new features like DPS and a custom trigger creations.

**Comment by cpand671** [comment]
Exactly like WoW HUDs. I believe it does show you how much you are healed for. I know it shows you he much you heal another person for. I recall my trio partners recounting what they were healed for.

I think if your were to implement it you should do the 3 overlays and not cram it into one. Colors code it like WoW.

Left Incoming:
- Red incoming damage or absorbed damage
- Fancy extra color coded spell damage based on type
- Green incoming heals

Right Outgoing:
- White outgoing damage (if you want to be fancy you can track double attacks and by seeing if there was another damage number within a certain millisecond and label it as double attack, you can also label ripostes)
- Yellow outgoing abilities (kick, bash, slam, monk abilities etc.) and spell damage
- if you want to be fancy with spell damage you can color code it based on damage type (I.E. red for fire)
- Blue outgoing misses/resists

Center can be stuns, dodges, blocks

**Comment by nomns** [comment]
Alright.  I've made notes.  I would need some logs to simulate testing maybe.  Especially for the riposting, double attacking, discs, etc.  As I said, I don't have any melee worth noting, so I don't know how some of the combat text occurs.  I think discs are in the spells file as well.  These are the types of things I don't really have access to easy testing.

**Comment by cpand671** [comment]
I'll see what I can get for ya tomorrow night. No rush. Only do it if you want to. Don't want your hobby project to bum you out.

**Comment by nomns** [comment]
haha It's np.  Once I'm done with what I have written down for what I had in mind, I will def. be looking to implement new things just like this.

**Comment by nomns** [comment]
The original feature has been implemented and is in the v0.3-alpha release.
