### ISSUE TITLE
Map widow width is reset to 530 px on start

### ISSUE THREAD

**Issue by abinitio** [nomns/nparse#13]
If you reduce the size of the map window and restart nParse, the width is reset to 530 pixels wide.

![nparse map window](https://user-images.githubusercontent.com/3510811/49559278-63b94e80-f962-11e8-9a50-ba356857e9bc.gif)

Is this intended? It makes laying out UI elements a pain when the map window keeps resizing itself.

**Comment by nomns** [comment]
This is absolutely not intended and does not happen when I run from source.

Running from the executable, this does occur just like you are showing but not to the spells window.  Let me look into what is going on with this.  It may be because of the internal items sizing themself with old information.

I will work on making a new release hopefully by Sunday.  I have a couple more features implemented that I can push through with it.

Thanks for bringing this to my attention.

**Comment by nomns** [comment]
New version is out [0.5.1](https://github.com/nomns/nparse/releases/tag/0.5.1).

The bug you brought up should be fixed.  Also, going forward, whenever you install a new version, you shouldn't have to redo your window locations.
