### ISSUE TITLE
Spells not showing up

### ISSUE THREAD

**Issue by USMCbudder** [nomns/nparse#31]
The map portion works just fine, but the spell window is empty. When ever i cast a spell nothing goes into that window. I unzipped nParse into its own folder on my desk top then did the logs directory. Does the whole folder need to be in my eqp99 folder or is it ok on the desktop?
Thanks,
Ron

**Comment by nomns** [comment]
You can put the application where ever you want -- you should need to set where the logs directory is within the application.  It does not need to be in your p99 folder.

I think your issue is that your spells are not being logged.  Within the settings in Everquest, there should be a setting to filter certain items from the logs.  I think you need to ensure that spells are making it to the log file.

Please let me know!

**Comment by USMCbudder** [comment]
Ok that makes sense. Now the settings in the game or like in one of my folders for p99? Any idea where I could look? Sorry not very good at manipulating files and stuff. I just don’t want to screw the game up. I recall having a UI mod that I had to drop in the velious folder so I get the spell icons up top on my screen. Could my spell logs be in a different folder like that? Hmmm...
Thank you for the quick response. Name in game is Renlaan, 54 Druid if u ever need something!

**Comment by nomns** [comment]
No worries at all.  That's why I am here to help. :)  I would give you a shout in game, but I am really not able to play much anymore -- another reason why I haven't had time to develop this application more.

Another user had this issue.  I think the settings are here:

When you are playing Everquest, go to your options:
PC Spells under Options -> Filters - ensure this is not set to hide.

Make sure PC Spells on your Filters is not set to Hide.  It will stop your spell landing messages from showing up in the logs.  Without those messages, my application doesn't know to create a timer.

Please let me know if this works for you!

**Comment by USMCbudder** [comment]
OMFG you’re a genius! That fixed it! I had PC spells set to hide along with dmg over time spells, bard songs and a few others. I set them all to show! You rock man! May I suggest putting that in the instructions for others just in case they have theirs off too? 
  Thanks a ton!
Renlaan
