### ISSUE TITLE
Shaman Epic

### ISSUE THREAD

**Issue by Tidomann** [nomns/nparse#33]
In order to add https://wiki.project1999.com/Curse_of_the_Spirits to the spells data text, what would I need to append to the file?

**Comment by nomns** [comment]
I believe that is based off a clickie.  Clickie spells don't have a "you being casting".  You will need to add this as a custom trigger.

Feel free to reopen this if that is not the issue.

Thanks!

**Comment by Tidomann** [comment]
Absolutely correct. There is a "Your X begins to glow." and I could possibly map each item to their respective spells. I'll take a look at the source and see if it's viable to implement.

**Comment by nomns** [comment]
Feel free.  You could implement a system for this, the way in which the main casting system works within nparse is:
catch the "you begin casting" -> calculate casting time -> create a "window" in which the successful landing message would appear -> listen for that success message within that time window-> yes ? create timer : clear that trigger.

I think you would have to potentially workaround the "window."  I would say that creating custom timers within the settings window would be a lot easier with current features.  I have sadly had 0 time in the last year to work on this project due to personal and work stuff.  The development branch I was working on had full custom timers (sounds/message/timers) akin to Gina.  Some of it is final in the dev branch, some is not. I really wish I had had the time to finalize that aspect of it before life happened.
