### ISSUE TITLE
Clicky spells 

### ISSUE THREAD

**Issue by maqij** [nomns/nparse#5]
Clicky spells are not showing up in the spell list. I tested Grim Aura on the Shrunken Goblin Earring, Drones of Doom on Velious druid bracers, and the wrath of nature on the druid epic. Would it be possible to add clicky spells?

**Comment by nomns** [comment]
Currently, spells are only parsed when it sees you start to cast a spell (Pots work cause they have a cast message.).  This allows me to parse bard spells (bard spells soon), aoe casts (like wiz aoe snare) , group buffs (like potg), and to ensure that it is actually your spell being cast (without checking every parse for the thousands of spells in the spells_us.txt file).  If I check just for spell landings, for every line in your log file, things could get out of hand with parsing other people's casts and cpu usage.

I was hoping to get clickies and discs into a 'custom trigger' feature, where the user could choose which clickies they want to track -- since some clickies are not self only.  I have a couple things to finish (new map z system so you can track the layer of the map you are, sounds sounds sounds, but custom triggers are on my list).

Please let me know if this sounds good.   It was already a planned feature, so let me know if I covered what you were wanting above and I'll close the issue.

Thanks!

**Comment by nomns** [comment]
I am going to add "parse all spells" on you or on other automatically to the settings eventually.  I don't think its useful for casters because you will track everything at your level casting (but maybe useful if you want to track buffs being cast on yourself for warriors lets say)  -- even mobs casting on themselves/you will be tracked (at whatever character level you have listed on your spell tracker window).  I can colour them differently than your casts.

Clickies and the like should be added manually by user (or I may have templates for clickies) when the custom trigger feature is implemented (it will tie into spell calculations so you can ask it to calculate your clicky spell timer at your level).

Thanks for your suggestion.
