### ISSUE TITLE
Clicky items not showing up in parser

### ISSUE THREAD

**Issue by TVOps** [nomns/nparse#7]
I've noticed spells cast from a clicky item such as Jboots or Lodizal Shell Boots do not show up in the parser. In the spells_us.txt I see that both those spell text triggers are in there, they simply do not ever show in the parser. Any idea why the parser misses clicky items?

**Comment by nomns** [comment]
To differentiate between your casts and the casts of others, a dynamic trigger is created when you cast a spell which only parses the 1 exact spell you are casting based on the cast time of the spell.  Clickies do not have "You begin casting..." and a cast time, so they are not parsed at all.  Sow pots do have the standard "You being casting...," so that's why pots are parsed.  I'm not sure its feasible to lookup triggers for the thousands of different effects for every single line of text (imagine being in a raid).

On that note, I do want to add the ability to create custom triggers like Gina etc, so that you could create whatever extra triggers you want.  It would hopefully also involve linking to the spell file so you could look up effects from the spell file and "toggle" the ability to do the clickies you have created.   

As this is a hobby program, I got it as close to production usable as possible.  But unfortunately as a hobby program, other things have had priority and I haven't been able to complete the last few updates as of yet, but I do plan on doing so.  Hopefully the custom triggers and at least some sound!

Thanks for the comment and I hope everything else is working as intended!
